# Generated by Django 4.2.9 on 2024-04-20 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_beltanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='beltanalysis',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
